name: E2E Tests with Playwright

on:
  push:
    branches: [main, develop, perf-benchmarks-evidence]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Setup test database
        run: |
          cd backend
          python -c "from core.database import init_db; import asyncio; asyncio.run(init_db())"
        env:
          DATABASE_URL: sqlite:///./test_e2e.db
          DEBUG: 'true'

      - name: Run E2E tests
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          API_BASE_URL: http://localhost:8000
          FRONTEND_URL: http://localhost:3000
          KEEP_WEBHOOK_SECRET: test-secret-ci
          BEDROCK_AGENTCORE_ENABLED: 'false'
          CI: 'true'

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.browser }}
          path: |
            test-results/
            playwright-report/
          retention-days: 30

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate summary
        run: |
          echo "## E2E Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Tests completed across Chromium, Firefox, and WebKit" >> $GITHUB_STEP_SUMMARY
          
          if [ -d "playwright-results-chromium" ]; then
            echo "✅ Chromium tests completed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -d "playwright-results-firefox" ]; then
            echo "✅ Firefox tests completed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -d "playwright-results-webkit" ]; then
            echo "✅ WebKit tests completed" >> $GITHUB_STEP_SUMMARY
          fi

